cmake_minimum_required(VERSION 3.5.1)
set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(TOOLCHAIN_PREFIX x86_64-w64-mingw32)

set(CMAKE_C_COMPILER "${TOOLCHAIN_PREFIX}-gcc")
set(CMAKE_CXX_COMPILER "${TOOLCHAIN_PREFIX}-g++")


#message("CMAKE_SOURCE_DIR : ${CMAKE_SOURCE_DIR}")
#set(CMAKE_FIND_ROOT_PATH ${CMAKE_SOURCE_DIR}/x86_64-w64-mingw32) 
#message("CMAKE_FIND_ROOT_PATH ${CMAKE_FIND_ROOT_PATH}") 
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)

set(CMAKE_CROSS_COMPILING TRUE)
#set(CMAKE_FIND_LIBRARY_SUFFIXES ".a")
link_libraries(-static-libgcc -static-libstdc++)
