#!/bin/bash

[ ! -d SDL2 ] && mkdir SDL2

pushd SDL2

wget https://www.libsdl.org/release/SDL2-devel-2.0.10-mingw.tar.gz
tar -xvzf  SDL2-devel-2.0.10-mingw.tar.gz
rm SDL2-devel-2.0.10-mingw.tar.gz
mv SDL2-2.0.10 SDL2


wget https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-devel-2.0.15-mingw.tar.gz
tar -xvzf SDL2_ttf-devel-2.0.15-mingw.tar.gz
rm SDL2_ttf-devel-2.0.15-mingw.tar.gz
mv SDL2_ttf-2.0.15 SDL2_ttf

wget https://www.libsdl.org/projects/SDL_image/release/SDL2_image-devel-2.0.5-mingw.tar.gz
tar -xvzf SDL2_image-devel-2.0.5-mingw.tar.gz
rm SDL2_image-devel-2.0.5-mingw.tar.gz
mv SDL2_image-2.0.5 SDL2_image

wget https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-devel-2.0.4-mingw.tar.gz
tar -xvzf SDL2_mixer-devel-2.0.4-mingw.tar.gz
rm SDL2_mixer-devel-2.0.4-mingw.tar.gz
mv SDL2_mixer-2.0.4 SDL2_mixer

popd
