#!/bin/bash

[ ! -d SDL2 ] && mkdir SDL2

pushd SDL2

wget https://www.libsdl.org/release/SDL2-2.0.8.zip
unzip SDL2-2.0.8.zip 
rm SDL2-2.0.8.zip
mv SDL2-2.0.8 SDL2


wget https://www.libsdl.org/projects/SDL_ttf/release/SDL_ttf-2.0.11.zip
unzip SDL_ttf-2.0.11.zip
rm SDL_ttf-2.0.11.zip
mv SDL_ttf-2.0.11 SDL_ttf

popd
